package member;
import Delivery.DeliveryMainGUI;
/*
* To change this template, choose Tools | Templates
* and open the template in the editor.
*/
/**
* 회원가입 GUI * @author san
*/

public class MemberJoinForm extends javax.swing.JFrame {
	MemberProcessing memberJoinProcess; // 회원가입 처리 객체
	 DeliveryMainGUI deliveryMain; // 메인 메뉴
	 String name, loginId, password, address;
	 int payment;
	 /**
	 * Creates new form MemberJoinForm
	 */
	 public MemberJoinForm() {
	 initComponents();
	 memberJoinProcess = new MemberProcessing();
	 initpayment();
	 payment = 10; // 결제의 디폴트 값
	 address = "student";
	 }
	 /**
	 * This method is called from within the constructor to initialize the form. * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor. */
	 @SuppressWarnings("unchecked")
	 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	 private void initComponents() {
	 jLabel1 = new javax.swing.JLabel();
	 jLabel2 = new javax.swing.JLabel();
	 jLabel3 = new javax.swing.JLabel();
	 jLabel4 = new javax.swing.JLabel();
	 jLabel5 = new javax.swing.JLabel();
	 jLabel6 = new javax.swing.JLabel();
	 txtName = new javax.swing.JTextField();
	 txtPasswordVerification = new javax.swing.JTextField();
	 txtLoginID = new javax.swing.JTextField();
	 txtPassword = new javax.swing.JTextField();
	 cmbaddress = new javax.swing.JComboBox();
	 jLabel7 = new javax.swing.JLabel();
	 btnLoginApply = new javax.swing.JButton();
	 cmbpayment = new javax.swing.JComboBox();
	 setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	 jLabel1.setText("이름");
	 jLabel2.setText("주소");
	 jLabel3.setText("결제");
	 jLabel4.setText("ID");
	 jLabel5.setText("패스워드");
	 jLabel6.setText("패스워드확인");
	 txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
	 txtPasswordVerification.setHorizontalAlignment(javax.swing.JTextField.LEFT);
	 txtLoginID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
	 txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
	 cmbaddress.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "student", "professor", "laboror", 
	"farmer", "fisherman", "other" }));
	 cmbaddress.addItemListener(new java.awt.event.ItemListener() {
	 public void itemStateChanged(java.awt.event.ItemEvent evt) {
	 checkaddress(evt);
	 }
	 });
	 jLabel7.setFont(new java.awt.Font("굴림", 1, 18)); // NOI18N
	 jLabel7.setText("회원가입");
	 btnLoginApply.setText("회원가입신청");
	 btnLoginApply.addMouseListener(new java.awt.event.MouseAdapter() {
	 public void mouseClicked(java.awt.event.MouseEvent evt) {
	 memberJoinProcess(evt);
	 }
	 });
	 cmbpayment.addItemListener(new java.awt.event.ItemListener() {
	 public void itemStateChanged(java.awt.event.ItemEvent evt) {
	 paymentHandle(evt);
	 }
	 });
	 javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	 getContentPane().setLayout(layout);
	 layout.setHorizontalGroup(
	 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	 .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	 .addComponent(btnLoginApply)
	 .addGap(143, 143, 143))
	 .addGroup(layout.createSequentialGroup()
	 .addGap(87, 87, 87)
	 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
	 .addComponent(jLabel2)
	 .addComponent(jLabel4)
	 .addComponent(jLabel3)
	 .addComponent(jLabel5)
	 .addComponent(jLabel6)
	 .addComponent(jLabel1))
	 .addGap(66, 66, 66)
	 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	 .addComponent(txtPasswordVerification, javax.swing.GroupLayout.Alignment.TRAILING)
	 .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
	 .addComponent(txtLoginID, javax.swing.GroupLayout.Alignment.TRAILING)
	 .addComponent(txtName)
	 .addComponent(cmbaddress, 0, 187, Short.MAX_VALUE)
	 .addComponent(cmbpayment, 0, 187, Short.MAX_VALUE))
	 .addGap(44, 44, 44))
	 .addGroup(layout.createSequentialGroup()
	 .addGap(176, 176, 176)
	 .addComponent(jLabel7)
	 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	 );
	 layout.setVerticalGroup(
	 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	 .addGroup(layout.createSequentialGroup()
	 .addGap(15, 15, 15)
	 .addComponent(jLabel7)
	 .addGap(18, 18, 18)
	 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	 .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, 
	javax.swing.GroupLayout.PREFERRED_SIZE)
	 .addComponent(txtName))
	 .addGap(18, 18, 18)
	 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	 .addComponent(jLabel2)
	 .addComponent(cmbaddress))
	 .addGap(18, 18, 18)
	 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	 .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, 
	javax.swing.GroupLayout.PREFERRED_SIZE)
	 .addComponent(cmbpayment))
	 .addGap(18, 18, 18)
	 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	 .addGroup(layout.createSequentialGroup()
	 .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, 
	javax.swing.GroupLayout.PREFERRED_SIZE)
	 .addGap(18, 18, 18)
	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	 .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, 
	javax.swing.GroupLayout.PREFERRED_SIZE)
	 .addComponent(txtPassword))
	 .addGap(18, 18, 18)
	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	 .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, 
	javax.swing.GroupLayout.PREFERRED_SIZE)
	 .addComponent(txtPasswordVerification)))
	 .addGroup(layout.createSequentialGroup()
	 .addComponent(txtLoginID)
	.addGap(72, 72, 72)))
	 .addGap(18, 18, 18)
	 .addComponent(btnLoginApply)
	 .addGap(16, 16, 16))
	 );
	 pack();
	 }// </editor-fold>//GEN-END:initComponents
	 /**
	 * 회원 가입 신청 버튼을 눌렀을 때 처리하는 이벤트 리스너 메소드
	 * 회원가입 필드의 각 구성원 입력값 받음
	 * 각 필드에 대한 입력값 검사
	 * 입력값에 이상이 없는 경우
	 * memberJoinProcess 객체를 이용하여 회원가입 처리
	 * @param evt 
	 */
	 private void memberJoinProcess(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberJoinProcess
	 // TODO add your handling code here:
	 boolean flagName, flagLoginId, flagPassword, flagaddress, flagpayment;
	 int loginID;
	 
	 //회원가입 필드의 각 구성원 입력값 받음
	 loginId = txtLoginID.getText();
	 password = txtPassword.getText();
	 name = txtName.getText();
	 
	 // 각 필드에 대한 입력값 검사
	 flagLoginId = logingIdCheck(); 
	 flagPassword = passwordCheck();
	 flagName = nameCheck();
	 flagpayment = paymentCheck(); 
	 flagaddress = addressCheck();
	 // 입력값에 이상이 없는 경우 memberJoinProcess 객체를 이용하여 회원가입 처리
	 if (flagName && flagLoginId && flagPassword && flagaddress && flagpayment) {
	 loginID = memberJoinProcess.memberJoin(loginId, password, name, address, payment); 
	 if(loginID > 0) {
	 this.setVisible(false);
	 deliveryMain = new DeliveryMainGUI(loginId, loginID);
	 deliveryMain.setVisible(true);
	 }
	 } else {
	 reinput(); // 모든 필드 초기화
	 }
	 
	 }//GEN-LAST:event_memberJoinProcess
	 /**
	 * 주소 선택 콤보박스 선택했을 때 처리하는 이벤트 리스너 메소드
	 * @param evt 
	 */
	 private void checkaddress(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkaddress
	 // TODO add your handling code here:
	 address = evt.getItem().toString();
	 }//GEN-LAST:event_checkaddress
	 /**
	 * 결제 선택 콤보박스 선택했을 때 처리하는 이벤트 리스너 메소드
	 * @param evt 
	 */
	 private void paymentHandle(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_paymentHandle
	 // TODO add your handling code here:
	 payment = Integer.parseInt(evt.getItem().toString());
	 }//GEN-LAST:event_paymentHandle
	 // Variables declaration - do not modify//GEN-BEGIN:variables
	 private javax.swing.JButton btnLoginApply;
	 private javax.swing.JComboBox cmbpayment;
	 private javax.swing.JComboBox cmbaddress;
	 private javax.swing.JLabel jLabel1;
	 private javax.swing.JLabel jLabel2;
	 private javax.swing.JLabel jLabel3;
	 private javax.swing.JLabel jLabel4;
	 private javax.swing.JLabel jLabel5;
	 private javax.swing.JLabel jLabel6;
	 private javax.swing.JLabel jLabel7;
	 private javax.swing.JTextField txtLoginID;
	 private javax.swing.JTextField txtName;
	 private javax.swing.JTextField txtPassword;
	 private javax.swing.JTextField txtPasswordVerification;
	 // End of variables declaration//GEN-END:variables
	 /**
	 * 로그인 아이디 입력 유무 검사
	 * @return 
	 */
	 private boolean logingIdCheck() {
	 if(loginId.isEmpty()) {
	 return false;
	 } else {
	 return true;
	 }
	 }
	 /**
	 * 패스워드 입력 유무 검사
	 * @return 
	 */
	 private boolean passwordCheck() {
	 if(password.isEmpty()) {
	 return false;
	 } else {
	 return true;
	 } 
	 }
	 /**
	 * 이름 입력 유무 검사
	 * @return 
	 */
	 private boolean nameCheck() {
	 if (name.isEmpty()) {
	 return false;
	 } else {
	 return true;
	 }
	 }
	 /**
	 * 결제 유효성 검사
	 * @return 
	 */
	 private boolean paymentCheck() {
	 if (0 <= payment && payment > 125) {
	 return false;
	 } else {
	 return true;
	 } 
	 }
	 /**
	 * 주소 검사
	 * @return 
	 */
	 private boolean addressCheck() {
	 if (address.isEmpty()) {
	 return false;
	 } else {
	 return true;
	 }
	 }
	 /**
	 * 결제 콤보박스 리스트 초기화
	 */
	 private void initpayment() {
	 int i;
	 for(i = 5; i< 120; i++){
		 cmbpayment.addItem(i);
		 }
		 }
		 /**
		 * 입력값 초기화
		 */
		 private void reinput() {
		 txtLoginID.setText("");
		 txtPassword.setText("");
		 txtName.setText("");
		 txtPasswordVerification.setText("");
		 txtLoginID.setFocusable(true);
		 }
		 }




