package Delivery;

import Delivery.LoginForm;
//import Delivery.LoginProcessing;
import review.ReviewForm;



/**
* 배달 어플 시스템의 주화면
* 주화면에서 로그인화면, 검색, 주소지 설정, 리뷰확인, 장바구니 등의 화면을 * 호출 할 수 있다. * * @author Administrator
*/


public class DeliveryMainGUI extends javax.swing.JFrame {
	LoginForm loginform;
	ReviewForm reviewform;
	String loginId; // 로그인 ID
	String name; // 로그인 이름
	 //LoginProcessing login; // 로그인 처리 객체
	 

/**
* Creates new form DeliveryMainGUI */
	 public DeliveryMainGUI() {
		 initComponents(); 
		 loginform = new LoginForm(); // 로그인 화면 객체
		 reviewform = new ReviewForm(); //리뷰 화면 객체
	 }
	 
/**
* DeliveryMainGUI 폼 생성
*
* @param loginId 로그인 아이디
*/
	 
	 public DeliveryMainGUI(String loginId, int accountId) {
		 this.loginId = loginId; // 로그인 아이디	
		 //login = new LoginProcessing(); // 로그인 처리 객체
		 initComponents(); // GUI 초기화
	 }
	 
/**
* This method is called from within the constructor to initialize the form. * WARNING: Do NOT modify this code. The content of this method is always
* regenerated by the Form Editor. */
	 
//@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

	 private void initComponents() {
		 jLabel1 = new javax.swing.JLabel();		
		 btnSetAdd = new javax.swing.JButton();
		 btnReview = new javax.swing.JButton();
		 btnBasket = new javax.swing.JButton();
		 btnLogin = new javax.swing.JButton();
		 btnSearch = new javax.swing.JButton();
		 txtSearch = new javax.swing.JTextField();
		 setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);				 
		
		 btnSetAdd.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
		 btnSetAdd.setText("주소지 수정");
		 btnSetAdd.addMouseListener(new java.awt.event.MouseAdapter() {
			 /*
			 public void mouseClicked(java.awt.event.MouseEvent evt) {
				 	setAdd(evt);
				 }
			  */
			 });
		 btnReview.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
		 btnReview.setText("리뷰확인");		 
		 btnReview.addMouseListener(new java.awt.event.MouseAdapter() {
			 public void mouseClicked(java.awt.event.MouseEvent evt) {
				 reviewform(evt);
			 	}
		 	});
		 
		 btnBasket.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
		 btnBasket.setText("장바구니");		 
		 btnBasket.addMouseListener(new java.awt.event.MouseAdapter() {
			 /*
			 public void mouseClicked(java.awt.event.MouseEvent evt) {
				 basket(evt);
			 	}
			 */
		 	});
		 
		 btnLogin.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
		 btnLogin.setText("로그인/회원가입");
		 btnLogin.setToolTipText("");
		 btnLogin.setActionCommand("");
		 btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {			 
		 public void mouseClicked(java.awt.event.MouseEvent evt) {
			 		loginform(evt);
			 	}
			 	
			 });
		 btnSearch.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
		 btnSearch.setText("검색");
		 txtSearch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		 txtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		 
		 setTitle("IT 배달 어플");
		 
		 javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		 getContentPane().setLayout(layout);
		 
		 layout.setHorizontalGroup(				 
				 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						 .addGroup(layout.createSequentialGroup()
							 .addGap(18, 18, 18)
							 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)									
									 .addGroup(layout.createSequentialGroup()
										.addGap(180,180,180)
										.addComponent(btnLogin))
									 .addGroup(layout.createSequentialGroup()
										.addComponent(txtSearch)
										.addComponent(btnSearch)
										.addGap(18,18,18))									 
									 .addGroup(layout.createSequentialGroup()
										.addComponent(btnSetAdd)
										.addGap(18, 18, 18)
										.addComponent(btnReview)
										.addGap(18, 18, 18)
										.addComponent(btnBasket)
										.addGap(18, 18, 18))
									 )								 
						 )
				 );
		
		 
		 
		 layout.setVerticalGroup(
				 layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 	.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
				 			
				 			.addGap(18, 18, 18)
				 			.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				 					.addComponent(btnLogin,javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)			 					
				 					)
				 			.addGap(18, 18, 18)
				 			.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				 					.addComponent(btnSearch)
				 					.addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				 			.addGap(18, 18, 18)
				 			.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
				 					.addComponent(btnSetAdd)
				 					.addComponent(btnReview)
				 					.addComponent(btnBasket, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
				 					
				 			.addGap(58, 58, 58))
				 			);				 						
		 pack();
	 }// </editor-fold>//GEN-END:initComponents

/**
* 리뷰확인 눌렀을 때 처리하는 이벤트 리스너 메소드
* 로그인 아이디를 이용하여 reviewForm 객체를 생성하고
* reviewScreen 객체를 호출한다. * @param evt 
*/


	private void reviewform(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_review
		// TODO add your handling code here:
		this.setVisible(false);
		reviewform.setVisible(true); 
	}//GEN-LAST:event_review

	 
/**
* 로그인 눌렀을 때 처리하는 이벤트 리스너 메소드
* LoginForm 객체를 호출한다. * @param evt 
*/
	  

	 private void loginform(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberJoin
		 // TODO add your handling code here: 
		 this.setVisible(false);
		 loginform.setVisible(true);
		 }//GEN-LAST:event_memberJoin
	 
	 
	 //메인 함수
	 
	 public static void main(String args[]) {
		 /* Set the Nimbus look and feel */
		 //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		 try {
			 for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			 if ("Nimbus".equals(info.getName())) {
					 javax.swing.UIManager.setLookAndFeel(info.getClassName());
					 break;
				 }
			 }
		 } 
		 catch (ClassNotFoundException ex) {
			 java.util.logging.Logger.getLogger(DeliveryMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		 } 
		 catch (InstantiationException ex) {
			 java.util.logging.Logger.getLogger(DeliveryMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		 } 
		 catch (IllegalAccessException ex) {
			 java.util.logging.Logger.getLogger(DeliveryMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		 } 
		 catch (javax.swing.UnsupportedLookAndFeelException ex) {
			 java.util.logging.Logger.getLogger(DeliveryMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		 }
		 //</editor-fold>
		 /* Create and display the form */
			 java.awt.EventQueue.invokeLater(new Runnable() {
				 public void run() {
					 new DeliveryMainGUI().setVisible(true);
				 }
			 });
		 }
	 
// Variables declaration - do not modify//GEN-BEGIN:variables
	 
private javax.swing.JButton btnReview;
private javax.swing.JButton btnLogin;
private javax.swing.JButton btnSearch;
private javax.swing.JButton btnSetAdd;
private javax.swing.JButton btnBasket;
private javax.swing.JLabel jLabel1;
private javax.swing.JTextField txtSearch;
// End of variables declaration//GEN-END:variables
}
